- hosts: obsd-build
  gather_facts: true
  tasks:

  # - name: find out device for /usr/obj
  #   shell: |
  #     mount |grep /usr/obj|sed "s#\(/dev/\)\([^ ]*\).*#\1r\2#"
  #   register: objdev


  - name: umount obj
    mount:
      path: /usr/obj
      state: unmounted

  #~# find /usr/obj -type f|xargs stat -f "%z"|awk '{s+=$1}END{print s/NR}'
  #67129.9
  #~# find . -type f|sed 's#/[^/]*$##'|sort|uniq -c|awk '{s+=$1}END{print s/NR}'
  #15.9612
  - name: format /usr/obj
    command: newfs -g67000 -h16 -otime /dev/rsd0h

  - name: mount obj
    command: mount /usr/obj

  - name: create /usr/obj directories
    block:
      - file:
          path: "/usr/obj/{{ item }}"
          state: directory
          owner: build
          group: wobj
          mode: 0770
        with_items:
          - bsd
          - xenocara
      - file:
          path: "/usr/obj/{{ item }}"
          state: directory
          owner: _pbuild
          group: wobj
          mode: 0775
        with_items:
          - ports
          - ports.bulk
          - ports.update
          - ports.locks

  - name: mount mfs for /usr/obj
    shell: umount /usr/obj &&  mount_mfs -P/dev/sd0h -s4G -onosuid,noperm,nodev,rw swap /usr/obj
