---
- hosts: obsd-build
  gather_facts: false
  tasks:
  - name: save old ssh settings
    set_fact:
      old_ssh_key: "{{ansible_ssh_private_key_file}}"
      ansible_ssh_pass: root
      ansible_ssh_private_key_file: ""

  - name: set installurl
    raw: echo {{openbsd_mirror}}/pub/OpenBSD > /etc/installurl

  - name: install python
    raw: pkg_add python27

  - name: provision ssh pubkey
    authorized_key:
      user: root
      key: "{{ lookup('file', playbook_dir+'/keys/obsd-build-access.pub') }}"

  - name: restore ssh settings
    set_fact:
      ansible_ssh_private_key_file: "{{old_ssh_key}}"
      old_ssh_key: ""
      ansible_ssh_pass: root

  - name: install needed packages
    openbsd_pkg:
      name: "{{ item }}"
      state: present
      build: no
    with_items:
      - vim--no_x11
      - git
      - mercurial

  - name: install system config files
    block:
      - copy:
          src: "{{ item.src }}"
          dest: "{{ item.dst }}"
          owner: "{{ item.owner|default(omit) }}"
          group: "{{ item.group|default(omit) }}"
          mode: "{{ item.mode|default(0640) }}"
          force: yes
        with_items:
          - src: files/mk.conf
            dst: /etc/mk.conf
          - src: files/man.conf
            dst: /etc/man.conf
          - src: files/doas.conf
            dst: /etc/doas.conf
      - file: state=directory dest=/var/downloads mode=0775

  - name: install root's config files
    block:
      - blockinfile:
          insertafter: EOF
          path: /root/.profile
          content: "{{ lookup('file', 'files/root-profile.snip') }}"
      - copy:
          src: "{{ item.src }}"
          dest: "{{ item.dst }}"
          owner: "root"
          group: "wheel"
          mode: 0600
          force: yes
        with_items:
          - src: files/root-kshrc
            dst: /root/.kshrc
          - src: files/root-vimrc
            dst: /root/.vimrc
          - src: files/root-tmux.conf
            dst: /root/.tmux.conf

  - name: enable /dest mfs mount
    block:
      - file:
          path: "{{ item }}"
          state: directory
          owner: build
          mode: 0700
        with_items:
          - /dest
          - /var/dest
          - /var/dest/base
          - /var/dest/xbase
      - mount:
          state: mounted
          path: /dest
          src: swap
          fstype: mfs
          opts: "rw,nosuid,noperm,-P/var/dest,-s1.5G,noauto"
          dump: 0
          passno: 0

  - name: create /usr/obj directories
    block:
      - file:
          path: "/usr/obj/{{ item }}"
          state: directory
          owner: build
          group: wobj
          mode: 0775
        with_items:
          - bsd
          - xenocara
      - file:
          path: "/usr/obj/{{ item }}"
          state: directory
          owner: _pbuild
          group: _pbuild
          mode: 0775
        with_items:
          - ports
          - ports.bulk
          - ports.update
          - ports.locks

  - name: create misc data directories
    file:
      path: "{{ item }}"
      state: directory
      owner: _pbuild
      group: _pbuild
      mode: 0770
    with_items:
      - /var/ports
      - /var/ports/plist
      - /var/ports/distfiles
      - /var/ports/packages
      - /var/release

  - name: create directories for sources
    block:
      - file:
          path: "{{ item.path }}"
          state: directory
          owner: "{{ item.owner|default('build') }}"
          group: wsrc
          mode: 0775
        with_items:
          - path: /usr/src
          - path: /usr/xenocara
          - path: /usr/ports
            owner: _pfetch
          - path: /usr/local/ports
            owner: _pfetch
          - path: /usr/local/ports/gh-wip
            owner: _pfetch
          - path: /usr/local/ports/my
            owner: _pfetch

  - name: checkout git ports repos
    block:
      - git:
          dest: /usr/local/ports/gh-wip
          repo: https://github.com/jasperla/openbsd-wip
      - git:
          dest: /usr/local/ports/my
          repo: https://pzskc383.dp.ua/code/openbsd-ports
    become: true
    become_user: _pfetch

  - name: remove /usr/xobj
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /usr/xobj

  - name: record CVS server ssh hostkey
    block:
      - file: state=touch path=/root/.ssh/known_hosts
      - shell: ssh-keygen -R {{openbsd_anoncvs}} 2>/dev/null
      - shell: ssh-keyscan {{openbsd_anoncvs}} 2>/dev/null >>/root/.ssh/known_hosts

  - name: checkout {{item}} from cvs
    command: cvs -qd anoncvs@{{openbsd_anoncvs}}:/cvs checkout -P {{item}}
    args:
      chdir: /usr
    with_items:
      - src
      - xenocara
      - ports

  - name: fix source permissions
    file:
      path: "{{ item.path }}"
      owner: "{{ item.owner }}"
      group: wsrc
      mode: u=rw,g=rw,o=r
      recurse: true
    with_items:
      - path: /usr/src
        owner: build
      - path: /usr/xenocara
        owner: build
      - path: /usr/ports
        owner: _pfetch

  - name: enable serial console on boot
    copy:
      dest: /etc/boot.conf
      src: boot.conf
      owner: root
      group: wheel
      mode: u=rw,go=r

  - name: install serial term size fix script
    copy:
      dest: /usr/local/bin/ttycom0fix.sh
      src: ttycom0fix.sh
      mode: u=rwx,go=rx
      owner: root
      group: bin

  - name: set up serial console
    lineinfile:
      path: /etc/ttys
      regexp: "^console"
      line: 'console "/usr/libexec/getty std.115200" vt220 on secure local'


