---
- hosts: all
  gather_facts: false
  vars:
    openbsd_mirror: ftp://ftp.icm.edu.pl
    openbsd_anoncvs: anoncvs.eu.openbsd.org

  tasks:
  - name: install needed packages
    openbsd_pkg:
      name: "{{ item }}"
      state: present
      build: no
    with_items:
      - vim--no_x11
      - git
      - mercurial

  - name: install system config files
    block:
      - copy:
          src: "{{ item.src }}"
          dest: "{{ item.dst }}"
          owner: "{{ item.owner|default(omit) }}"
          group: "{{ item.group|default(omit) }}"
          mode: "{{ item.mode|default(0640) }}"
          force: yes
        with_items:
          - src: files/mk.conf
            dst: /etc/mk.conf
          - src: files/man.conf
            dst: /etc/man.conf
          - src: files/doas.conf
            dst: /etc/doas.conf
      - file: state=directory dest=/var/downloads mode=0775

  - name: install root's config files
    block:
      - blockinfile:
          insertafter: EOF
          path: /root/.profile
          content: "{{ lookup('file', 'files/root-profile.snip') }}"
      - copy:
          src: "{{ item.src }}"
          dest: "{{ item.dst }}"
          owner: "root"
          group: "wheel"
          mode: 0600
          force: yes
        with_items:
          - src: files/root-kshrc
            dst: /root/.kshrc
          - src: files/root-vimrc
            dst: /root/.vimrc
          - src: files/root-tmux.conf
            dst: /root/.tmux.conf

  - name: enable /dest mfs mount
    block:
      - file:
          path: "{{ item }}"
          state: directory
          owner: build
          mode: 0700
        with_items:
          - /dest
          - /var/dest
          - /var/dest/base
          - /var/dest/xbase
      - mount:
          state: mounted
          path: /dest
          src: swap
          fstype: mfs
          opts: "rw,nosuid,noperm,-P/var/dest,-s1.5G,noauto"
          dump: 0
          passno: 0

  - name: create /usr/obj directories
    block:
      - file:
          path: "/usr/obj/{{ item }}"
          state: directory
          owner: build
          group: wobj
          mode: 0775
        with_items:
          - bsd
          - xenocara
      - file:
          path: "/usr/obj/{{ item }}"
          state: directory
          owner: _pbuild
          group: _pbuild
          mode: 0775
        with_items:
          - ports
          - ports.bulk
          - ports.update
          - ports.locks

  - name: create misc data directories
    file:
      path: "{{ item }}"
      state: directory
      owner: _pbuild
      group: _pbuild
      mode: 0770
    with_items:
      - /var/ports
      - /var/ports/plist
      - /var/ports/distfiles
      - /var/ports/packages
      - /var/release

  - name: create directories for sources
    block:
      - file:
          path: "{{ item.path }}"
          state: directory
          owner: "{{ item.owner|default('build') }}"
          group: wsrc
          mode: 0775
        with_items:
          - path: /usr/src
          - path: /usr/xenocara
          - path: /usr/ports
            owner: _pfetch
          - path: /usr/local/ports
            owner: _pfetch
          - path: /usr/local/ports/gh-wip
            owner: _pfetch
          - path: /usr/local/ports/my
            owner: _pfetch

  - name: checkout git ports repos
    block:
      - git:
          dest: /usr/local/ports/gh-wip
          repo: https://github.com/jasperla/openbsd-wip
      - git:
          dest: /usr/local/ports/my
          repo: https://pzskc383.dp.ua/code/openbsd-ports
    become: true
    become_user: _pfetch

  - name: remove /usr/xobj
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /usr/xobj

  - name: install 'cvs up' fixing script
    copy:
      src: files/cvsupfix.sh
      dest: /usr/local/bin/cvsupfix.sh
      owner: root
      group: bin
      mode: 0775
      force: yes

  - name: record CVS server ssh hostkey
    block:
      - shell: ssh-keygen -R anoncvs.eu.openbsd.org 2>/dev/null
      - shell: ssh-keyscan {{openbsd_anoncvs}} 2>/dev/null >>/root/.ssh/known_hosts

  - name: check if src already checked out
    command: test -d /usr/src/CVS
    register: cvscheck_src
    ignore_errors: true

  - name: check if xenocara already checked out
    command: test -d /usr/xenocara/CVS
    register: cvscheck_xenocara
    ignore_errors: true

  - name: check if ports already checked out
    command: test -d /usr/ports/CVS
    register: cvscheck_ports
    ignore_errors: true

  - name: checkout src from cvs
    block:
      - command: tar tzf /var/downloads/src.tar.gz
        register: tarcheck_src
      - command: tar tzf /var/downloads/sys.tar.gz
        register: tarcheck_sys
      - file: path=/var/downloads/src.tar.gz state=absent
        when: tarcheck_src|failed
      - file: path=/var/downloads/sys.tar.gz state=absent
        when: tarcheck_sys|failed
      - get_url:
          dest: /var/downloads/src.tar.gz
          url: "{{openbsd_mirror}}/pub/OpenBSD/6.1/src.tar.gz"
        when: tarcheck_src|failed
      - get_url:
          dest: /var/downloads/sys.tar.gz
          url: "{{openbsd_mirror}}/pub/OpenBSD/6.1/sys.tar.gz"
        when: tarcheck_sys|failed
      - shell: rm -rf /usr/src/*
      - command: tar xzf /var/downloads/src.tar.gz -C /usr/src
      - command: tar xzf /var/downloads/sys.tar.gz -C /usr/src
    when: cvscheck_src|failed

  - name: update /usr/src from cvs
    command: cvsupfix.sh anoncvs@{{openbsd_anoncvs}}:/cvs
    args:
      chdir: /usr/src

  - name: do initial cvs xenocara checkout
    block:
      - command: tar tzf /var/downloads/xenocara.tar.gz
        register: tarcheck_xenocara
      - file: path=/var/downloads/xenocara.tar.gz state=absent
        when: tarcheck_xenocara|failed
      - get_url:
          dest: /var/downloads/xenocara.tar.gz
          url: "{{openbsd_mirror}}/pub/OpenBSD/6.1/xenocara.tar.gz"
        when: tarcheck_xenocara|failed
      - shell: rm -rf /usr/xenocara/*
      - command: tar xzf /var/downloads/xenocara.tar.gz -C /usr
    when: cvscheck_xenocara|failed

  - name: update /usr/xenocara from cvs
    command: cvsupfix.sh anoncvs@{{openbsd_anoncvs}}:/cvs
    args:
      chdir: /usr/xenocara

  - name: do initial cvs ports checkout
    block:
      - command: tar tzf /var/downloads/ports.tar.gz
        register: tarcheck_ports
      - file: path=/var/downloads/ports.tar.gz state=absent
        when: tarcheck_ports|failed
      - get_url:
          dest: /var/downloads/ports.tar.gz
          url: "{{openbsd_mirror}}/pub/OpenBSD/snapshots/ports.tar.gz"
        when: tarcheck_ports|failed
      - shell: rm -rf /usr/ports/* /usr/ports/.*
      - command: tar xzf /var/downloads/ports.tar.gz -C /usr
    when: cvscheck_ports|failed

  - name: update /usr/ports from cvs
    command: cvsupfix.sh anoncvs@{{openbsd_anoncvs}}:/cvs
    args:
      chdir: /usr/ports

  - name: fix permissions
    file:
      path: "{{ item.path }}"
      owner: "{{ item.owner }}"
      group: wsrc
      mode: u=rw,g=rw,o=r
      recurse: true
    with_items:
      - path: /usr/src
        owner: build
      - path: /usr/xenocara
        owner: build
      - path: /usr/ports
        owner: _pfetch
