---
- hosts: obsd-build
  tasks:
  - name: update /usr/{{item}} from cvs
    command: cvs -qd anoncvs@{{openbsd_anoncvs}}:/cvs up -Pd
    args:
      chdir: /usr/{{item}}
    with_items:
      - src
      - xenocara
      - ports

  - name: checkout git ports repos
    block:
      - git:
          dest: /usr/local/ports/gh-wip
          repo: https://github.com/jasperla/openbsd-wip
      - git:
          dest: /usr/local/ports/my
          repo: https://pzskc383.dp.ua/code/openbsd-ports
    become: true
    become_user: _pfetch

  - name: fix permissions
    file:
      path: "{{ item.path }}"
      owner: "{{ item.owner }}"
      group: wsrc
      mode: u=rwX,g=rwX,o=rX
      recurse: true
    with_items:
      - path: /usr/src
        owner: build
      - path: /usr/xenocara
        owner: build
      - path: /usr/ports
        owner: _pfetch

  - name: clean directories
    shell: make clean >/dev/null
    args:
      chdir: "{{item}}"
    with_items:
      - /usr/src
      - /usr/xenocara
