Choose your keyboard layout = default
System hostname = obsd-build
Which network interface do you wish to configure? = vio0
IPv4 address for vio0 = dhcp
DNS domain name = virt
Password for root = root
Start sshd(8) by default = yes
Allow ssh root login = yes
Do you expect to run the X Window System? = no
Change the default console to com0? = yes
Which speed should com0 use? = 115200
What timezone are you in = Europe/Kiev
Which disk is the root disk? = sd0
Location of sets = http
HTTP proxy URL = none
Server = ftp.hostserver.de
Server directory = pub/OpenBSD/6.1/amd64
Set name(s) = -g* -x*
URL to autopartitioning template for disklabel = https://pzskc383.dp.ua/obsd-build/disklabel
Directory does not contain SHA256.sig. Continue without verification? = yes
