Choose your keyboard layout = default
System hostname = obsd-build
Which network interface do you wish to configure? = vio0
IPv4 address for vio0 = dhcp
IPv6 address for vio0 = rtsol
DNS domain name = virt
Password for root = root
Setup a user = no
Start sshd(8) by default = yes
Allow root ssh login = yes
Do you expect to run the X Window System? = no
What timezone are you in = Europe/Kiev
Which disk is the root disk? = sd0
Location of sets = $SET_LOCATION
Server = $MIRROR
Server directory = pub/OpenBSD/$ISO_PATH/amd64
Set name(s) = -g* -x*
URL to autopartitioning template for disklabel = http://10.0.2.2:8557/disklabel
Directory does not contain SHA256.sig. Continue without verification? = $VERIFY_SETS
