Choose your keyboard layout = default
System hostname = obsd-build
Which network interface do you wish to configure? = vio0
IPv4 address for vio0 = dhcp
IPv6 address for vio0 = none
DNS domain name = bsd.virt
Password for root = $ROOT_PASSWORD
Change the default console to com0 = yes
Which speed should com0 use = 115200
Public ssh key for root account = $SSH_PUBKEY
Setup a user = no
Start sshd(8) by default = yes
Allow root ssh login = prohibit-password
Do you expect to run the X Window System? = no
What timezone are you in = UTC
Which disk is the root disk? = sd0
Location of sets = cd0
Server = $MIRROR_HOST
Is the disk partition already mounted = no
Which disk contains the install media = cd0
Which cd0 partition has the install sets = a
Set name(s) = *
Set name(s) = done
URL to autopartitioning template for disklabel = file:/install_disklabel
Directory does not contain SHA256.sig. Continue without verification? = $VERIFY_SETS
