---
- hosts: buildmachines
  tasks:
  - name: install needed packages
    openbsd_pkg:
      name: "{{ item }}"
      state: present
      build: no
    with_items:
      - vim--no_x11
      - git
      - mercurial

  - name: install system config files
    block:
      - copy:
          src: "{{ item.src }}"
          dest: "{{ item.dst }}"
          owner: "{{ item.owner|default(omit) }}"
          group: "{{ item.group|default(omit) }}"
          mode: "{{ item.mode|default(0640) }}"
          force: yes
        with_items:
          - src: files/mk.conf
            dst: /etc/mk.conf
          - src: files/man.conf
            dst: /etc/man.conf
          - src: files/doas.conf
            dst: /etc/doas.conf
      - file:
          dest: /etc/installurl
          content: |
            "{{ hostvars[openbsd_installurl] }}"
          mode: 0640

  - name: install root's config files
    block:
      - blockinfile:
          insertafter: EOF
          path: /root/.profile
          content: "{{ lookup('file', 'files/root-profile.snip') }}"
      - copy:
          src: "{{ item.src }}"
          dest: "{{ item.dst }}"
          owner: "root"
          group: "wheel"
          mode: 0600
          force: yes
        with_items:
          - src: files/root-kshrc
            dst: /root/.kshrc
          - src: files/root-vimrc
            dst: /root/.vimrc
          - src: files/root-tmux.conf
            dst: /root/.tmux.conf

  - name: enable /dest mfs mount
    block:
      - file:
          path: "{{ item }}"
          state: directory
          owner: build
          mode: 0700
        with_items:
          - /dest
          - /var/dest
          - /var/dest/base
          - /var/dest/xbase
      - mount:
          state: mounted
          path: /dest
          src: swap
          fstype: mfs
          opts: "rw,nosuid,noperm,-P/var/dest,-s1.5G,noauto"
          dump: 0
          passno: 0

  - name: create /usr/obj directories
    block:
      - file:
          path: "/usr/obj/{{ item }}"
          state: directory
          owner: build
          group: wobj
          mode: 0775
        with_items:
          - bsd
          - xenocara
      - file:
          path: "/usr/obj/{{ item }}"
          state: directory
          owner: _pbuild
          group: _pbuild
          mode: 0775
        with_items:
          - ports
          - ports.bulk
          - ports.update
          - ports.locks

  - name: create misc data directories
    file:
      path: "{{ item }}"
      state: directory
      owner: _pbuild
      group: _pbuild
      mode: 0770
    with_items:
      - /var/ports
      - /var/ports/plist
      - /var/ports/distfiles
      - /var/ports/packages
      - /var/release

  - name: create directories for sources
    block:
      - file:
          path: "{{ item.path }}"
          state: directory
          owner: "{{ item.owner|default('build') }}"
          group: wsrc
          mode: 0775
        with_items:
          - path: /usr/src
          - path: /usr/xenocara
          - path: /usr/ports
            owner: _pfetch
          - path: /usr/local/ports
            owner: _pfetch
          - path: /usr/local/ports/gh-wip
            owner: _pfetch
          - path: /usr/local/ports/my
            owner: _pfetch

  - name: checkout git ports repos
    block:
      - git:
          dest: /usr/local/ports/gh-wip
          repo: https://github.com/jasperla/openbsd-wip
      - git:
          dest: /usr/local/ports/my
          repo: https://pzskc383.dp.ua/code/openbsd-ports
    become: true
    become_user: _pfetch

  - name: remove /usr/xobj
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /usr/xobj

  - name: check for already checked out sources
    stat:
      path: "/usr/{{ item }}/CVS"
    with_items:
      - src
      - xenocara
      - ports
    register: cvs_check

  - name: dump
    debug:
      var: cvs_check
