SUDO=doas

KEEPKERNELS=yes
NOPROFILE=yes
PIPE=-pipe

LLVM_ARCHS=X86
XENOCARA_BUILD_DRI=yes
VIDEO_DRV_amd64=xf86-video-vesa xf86-video-vmware xf86-video-wsfb xf86-video-wsudl
VULKAN_DRIVERS=no
DRI_DRIVERS=swrast
GALLIUM_DRIVERS=swrast


PORTSDIR_PATH=/usr/src/ports/mystuff:${PORTSDIR}:/usr/src/ports/openbsd-wip

# FETCH_PACKAGES=
PORTS_PRIVSEP=Yes

#WRKOBJDIR=/obj/ports
#BULK_COOKIES_DIR=/obj/ports.bulk
#UPDATE_COOKIES_DIR=/obj/ports.update
#LOCKDIR=/obj/ports.locks
#LOGDIR=/obj/ports.logs

#DISTDIR=/var/ports/distfiles
#PLIST_REPOSITORY=/var/ports/plist
#PACKAGE_REPOSITORY=/var/ports/packages
