Choose your keyboard layout = default
System hostname = obsd-build
Which network interface do you wish to configure? = vio0
IPv4 address for vio0 = dhcp
IPv6 address for vio0 = rtsol
DNS domain name = virt
Password for root = *************
Public ssh key for root account = $SSH_KEY
Setup a user = no
Start sshd(8) by default = yes
Allow root ssh login = yes
Do you expect to run the X Window System? = no
What timezone are you in = Europe/Kiev
Which disk is the root disk? = sd0
Location of sets = http
Server = $MIRROR
Server directory = /$MIRROR_PATH
Set name(s) = -g* -x*
URL to autopartitioning template for disklabel = http://10.0.2.2/disklabel
Directory does not contain SHA256.sig. Continue without verification? = no
