SUDO=/usr/bin/doas
FETCH_PACKAGES=yes
PORTSDIR_PATH=/usr/local/ports/my:${PORTSDIR}:/usr/local/ports/gh-wip
#COPTS=-march=native

BUILDUSER=build
KEEPKERNELS=yes

WRKOBJDIR=/usr/obj/ports
BSDOBJDIR=/usr/obj/bsd
XOBJDIR=/usr/obj/x11

BULK_COOKIES_DIR=/usr/obj/ports.bulk
UPDATE_COOKIES_DIR=/usr/obj/ports.update
LOCKDIR=/usr/obj/ports.locks

PLIST_REPOSITORY=/var/ports/plist
DISTDIR=/var/ports/distfiles
PACKAGE_REPOSITORY=/var/ports/packages
