---
- name: Building sources
  hosts: obsd-build
  gather_facts: true
  tasks:
    # - name: Mount /usr/src ramdisk
    #   ansible.builtin.shell: umount /usr/src &&  mount_mfs -P/dev/sd0f -s1G -onosuid,noperm,nodev,rw swap /usr/src

    - name: Make kernel obj
      ansible.builtin.shell:
        cmd: make obj >/dev/null
        chdir: /sys/arch/amd64/compile/GENERIC.MP
        creates: /usr/obj/bsd/sys/arch/amd64/compile/GENERIC.MP

    - name: Make kernel config
      ansible.builtin.shell:
        cmd: make config >/dev/null
        chdir: /sys/arch/amd64/compile/GENERIC.MP
        creates: /usr/obj/bsd/sys/arch/amd64/compile/GENERIC.MP/Makefile
      become: true
      become_user: build

    - name: Make kernel
      ansible.builtin.shell:
        cmd: make >/dev/null
        chdir: /sys/arch/amd64/compile/GENERIC.MP
        creates: /usr/obj/bsd/sys/arch/amd64/compile/GENERIC.MP/bsd

    - name: Check if our kernel is fresh
      ansible.builtin.command: diff /bsd.booted /usr/obj/bsd/sys/arch/amd64/compile/GENERIC.MP/bsd
      ignore_errors: true
      register: kerneldiffcheck
      changed_when: kerneldiffcheck.rc != 0

    - name: Install kernel
      ansible.builtin.shell:
      args:
        cmd: make install >/dev/null
        chdir: /sys/arch/amd64/compile/GENERIC.MP
      register: kernelinstall
      when: kerneldiffcheck.rc != 0
      changed_when: kernelinstall.rc == 0

    - name: Reboot machine
      ansible.builtin.shell:
      args:
        cmd: (sleep 5 && reboot) &
      when: kerneldiffcheck.rc != 0
      changed_when: true

    - name: Wait for it
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 900
      delegate_to: localhost
      when: kerneldiffcheck.rc != 0

    # - name: Mount /usr/src ramdisk
    #   ansible.builtin.shell: umount /usr/src &&  mount_mfs -P/dev/sd0f -s1G -onosuid,noperm,nodev,rw swap /usr/src

    - name: Make base system obj
      ansible.builtin.shell:
        cmd: make obj >/dev/null
        chdir: /usr/src
        creates: /usr/obj/bsd/regress

    - name: Build base system
      ansible.builtin.shell:
        cmd: make build >/dev/null
        chdir: /usr/src
        creates: /var/sysmerge/etc.tgz

    - name: Check if any files need merging
      ansible.builtin.command:
        cmd: sysmerge -b
      changed_when: sysmergecheck.rc == 0
      register: sysmergecheck
      ignore_errors: true

    - name: Run MAKEDEV all
      ansible.builtin.command:
        cmd: /bin/sh MAKEDEV all
        chdir: /dev
      changed_when: true

    - name: Mount /dest # noqa command-instead-of-module
      ansible.builtin.command:
        cmd: mount /dest
      changed_when: true

    - name: Make base release
      ansible.builtin.shell:
        cmd: |-
          make RELEASEDIR=/var/release DESTDIR=/dest/base release >/dev/null
        chdir: /usr/src/etc
      changed_when: true

    - name: Check file list # noqa command-instead-of-shell
      ansible.builtin.shell:
        cmd: |-
          RELEASEDIR=/var/release
          DESTDIR=/dest/base
          /bin/sh checkflist
        chdir: /usr/src/distrib/sets
      changed_when: true

    # - name: Mount /usr/xenocara ramdisk
    #   ansible.builtin.shell: umount /usr/xenocara &&  mount_mfs -P/dev/sd0g -s1G -onosuid,nodev,rw,exec swap /usr/xenocara

    - name: Bootstrap xenocara
      ansible.builtin.shell: make bootstrap >/dev/null
      args:
        chdir: /usr/xenocara
      changed_when: true

    - name: Make xenocara obj
      ansible.builtin.shell:
        cmd: make obj >/dev/null
        chdir: /usr/xenocara
        creates: /usr/obj/x11/distrib/notes
      changed_when: true

    - name: Build xenocara
      ansible.builtin.shell: make build >/dev/null
      args:
        chdir: /usr/xenocara
      changed_when: true

    - name: Make xenocara release
      ansible.builtin.shell: env DESTDIR=/dest/xbase RELEASEDIR=/var/release make release >/dev/null
      args:
        chdir: /usr/xenocara
      changed_when: true

    - name: Check xenocara release
      ansible.builtin.shell: env DESTDIR=/dest/xbase RELEASEDIR=/var/release make checkdist >/dev/null
      args:
        chdir: /usr/xenocara
      changed_when: true

    - name: Create install images
      ansible.builtin.shell:
        cmd: env RELDIR=/var/release RELXDIR=/var/release make >/dev/null
        chdir: /usr/src/distrib/amd64/iso
      changed_when: true

    - name: Install install images (...)
      ansible.builtin.shell:
        cmd: env RELDIR=/var/release RELXDIR=/var/release make install >/dev/null
        chdir: /usr/src/distrib/amd64/iso
      changed_when: true
