---
- hosts: obsd-build
  gather_facts: true
  tasks:
    - name: Mount /usr/src ramdisk
      ansible.builtin.shell: umount /usr/src &&  mount_mfs -P/dev/sd0f -s1G -onosuid,nodev,rw swap /usr/src
    - name: Mount /usr/xenocara ramdisk
      ansible.builtin.shell: umount /usr/xenocara &&  mount_mfs -P/dev/sd0g -s1G -onosuid,nodev,rw swap /usr/xenocara
    - name: Umount obj
      ansible.posix.mount:
        path: /usr/obj
        state: unmounted

    - name: Format /usr/obj
      ansible.builtin.command: newfs -g67000 -h16 -otime /dev/rsd0h
    - name: Mount obj
      ansible.builtin.command: mount /usr/obj
    - name: Create /usr/obj directories
      block:
        - ansible.builtin.file:
            path: /usr/obj/{{ item }}
            state: directory
            owner: build
            group: wobj
            mode: "0770"
          with_items:
            - bsd
            - x11
        - ansible.builtin.file:
            path: /usr/obj/{{ item }}
            state: directory
            owner: _pbuild
            group: wobj
            mode: "0775"
          with_items:
            - ports
            - ports.bulk
            - ports.update
            - ports.locks

    - name: Mount mfs for /usr/obj
      ansible.builtin.shell: umount /usr/obj &&  mount_mfs -P/dev/sd0h -s4G -onosuid,nodev,rw,exec swap /usr/obj
