- hosts: obsd-build
  gather_facts: true
  tasks:

  - name: mount /usr/src ramdisk
    shell: umount /usr/src &&  mount_mfs -P/dev/sd0f -s1G -onosuid,nodev,rw swap /usr/src

  - name: mount /usr/xenocara ramdisk
    shell: umount /usr/xenocara &&  mount_mfs -P/dev/sd0g -s1G -onosuid,nodev,rw swap /usr/xenocara

  - name: umount obj
    mount:
      path: /usr/obj
      state: unmounted

  - name: format /usr/obj
    command: newfs -g67000 -h16 -otime /dev/rsd0h

  - name: mount obj
    command: mount /usr/obj

  - name: create /usr/obj directories
    block:
      - file:
          path: "/usr/obj/{{ item }}"
          state: directory
          owner: build
          group: wobj
          mode: 0770
        with_items:
          - bsd
          - x11
      - file:
          path: "/usr/obj/{{ item }}"
          state: directory
          owner: _pbuild
          group: wobj
          mode: 0775
        with_items:
          - ports
          - ports.bulk
          - ports.update
          - ports.locks

  - name: mount mfs for /usr/obj
    shell: umount /usr/obj &&  mount_mfs -P/dev/sd0h -s4G -onosuid,nodev,rw,exec swap /usr/obj
