---
- name: Update sources
  hosts: obsd-build
  tasks:
    - name: Fix mounts
      ansible.builtin.shell: umount /usr/src && mount /usr/src && umount /usr/xenocara && mount /usr/xenocara
      changed_when: false

    - name: "CVS update: {{ item }}"
      ansible.builtin.command: cvs -qd anoncvs@{{ openbsd_anoncvs }}:/cvs up -Pd
      args:
        chdir: /usr/{{ item }}
      loop:
        - src
        - xenocara
        - ports
      become: true
      become_user: srcfetch
      changed_when: true

    - name: Checkout git ports repos
      become: true
      become_user: srcfetch

      block:
        - name: Install my ports tree # noqa: latest
          ansible.builtin.git:
            dest: /usr/local/ports/my
            repo: https://pzskc383.dp.ua/code/openbsd-ports

    - name: Fix permissions
      ansible.builtin.file:
        path: "{{ item }}"
        owner: srcfetch
        group: wsrc
        mode: u=grwX,o=rX
        recurse: true
      loop:
        - /usr/src
        - /usr/xenocara
        - /usr/ports
        - /usr/local/ports/my
        - /usr/local/ports/gh-wip
