---
- hosts: obsd-build
  tasks:
    - name: Fix mounts
      ansible.builtin.shell: umount /usr/src && mount /usr/src && umount /usr/xenocara && mount /usr/xenocara
    - name: Update /usr/{{item}} from cvs
      ansible.builtin.command: cvs -qd anoncvs@{{openbsd_anoncvs}}:/cvs up -Pd
      args:
        chdir: /usr/{{ item }}
      with_items:
        - src
        - xenocara
        - ports
      become: true
      become_user: srcfetch

    - name: Checkout git ports repos
      become: true
      become_user: srcfetch

      block:
        - ansible.builtin.git:
            dest: /usr/local/ports/gh-wip
            repo: https://github.com/jasperla/openbsd-wip
        - ansible.builtin.git:
            dest: /usr/local/ports/my
            repo: https://pzskc383.dp.ua/code/openbsd-ports
    - name: Fix permissions
      ansible.builtin.file:
        path: "{{ item }}"
        owner: srcfetch
        group: wsrc
        mode: u=grwX,o=rX
        recurse: true
      with_items:
        - /usr/src
        - /usr/xenocara
        - /usr/ports
        - /usr/local/ports/my
        - /usr/local/ports/gh-wip
