config {
    hostname anoncvs.eu.openbsd.org
    base-prefix /var/cvs
    compress

    collection {
        name openbsd-ports release rcs
    }
    collection {
        name openbsd-src release rcs
    }
    collection {
        name openbsd-xenocara release rcs
    }
}
