unbind C-b
set -g prefix C-a
bind-key C-a last-window
bind-key a send-prefix

set -g default-command "${SHELL}"
set -g history-limit 8192
set -g history-file ~/.local/share/tmux/history
set -g set-clipboard on
set -g focus-events on
set -g bell-action any
set -g status-keys vi
setw -g mode-keys vi
setw -g monitor-activity off
set -ga terminal-overrides ',rxvt*:Cc=\E]12;%p1%s\007:Cr=\E]12;black\007'

set -g set-titles on
set -g set-titles-string "#W tmux:#S :#I.#P"
set -g status-left "#S "
set -g status-right "#{=21:pane_title} %d%a %H%M"

set -g status-position bottom
set -g status-fg white
set -g status-bg black
set -g window-status-fg white
set -g window-status-bg black
set -g window-status-current-fg brightgreen
set -g window-status-current-bg black
set -g message-fg brightyellow
set -g message-bg black
set -g pane-active-border-style fg=green
set -g pane-border-style fg=default

bind r source-file ~/.tmux.conf \; display-message "config reloaded"
bind C-s set status
bind S choose-session

bind v split-window -h
bind s split-window
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind h select-pane -L
bind C-h select-pane -L
bind j select-pane -D
bind C-j select-pane -D
bind k select-pane -U
bind C-k select-pane -U
bind l select-pane -R
bind C-l select-pane -R
bind -r H resize-pane -L "$pane_resize"
bind -r J resize-pane -D "$pane_resize"
bind -r K resize-pane -U "$pane_resize"
bind -r L resize-pane -R "$pane_resize"
